import type { CatalogCategory, CatalogProduct } from "./types";

export const exampleCategories: CatalogCategory[] = [
  { name: "Adesivos", slug: "adesivos", description: "Adesivos personalizados para diferentes usos e superfícies." },
  { name: "Garrafas", slug: "garrafas", description: "Garrafas térmicas personalizadas em diferentes modelos e cores." },
  { name: "3D", slug: "3d", description: "Produtos e peças personalizados com impressão 3D." },
  { name: "PVC e Ímã", slug: "pvc-e-ima", description: "Produtos personalizados em PVC e ímã." },
  { name: "Canecas", slug: "canecas", description: "Canecas personalizadas com diferentes técnicas de aplicação." },
  { name: "Outros", slug: "outros", description: "Outros serviços gráficos e de comunicação visual." },
];

const generalText = "Outros serviços gráficos e de comunicação visual. Consulte a equipe pelo WhatsApp para explicar o que você precisa.";
const engravingFonts = ["WEDDING BY MANDALA", "DOGGIE", "COMIC SANS MS", "SERINAH", "ANANDA", "PEPERNOTES", "VAGROUNDED BT", "GAMALIYA", "CHEDDAR JACK", "CAVIAR DREAMS", "CANDY ROUND BTN", "BABY ALEHA", "Nenhuma delas"];
const engravingOptions = [
  { name: "Nome para gravação", type: "text" as const, isRequired: true, choices: [] as string[] },
  { name: "Fonte da gravação", isRequired: true, choices: engravingFonts },
];

export const exampleProducts: CatalogProduct[] = [
  {
    name: "Adesivo vinil brilho", slug: "adesivo-vinil-brilho", category: exampleCategories[0],
    shortDescription: "Adesivo de vinil brilho, impermeável e com excelente durabilidade.",
    description: "Adesivo de vinil brilho impermeável e com excelente durabilidade. Informe as medidas, a quantidade e escolha com corte ou sem corte. O tamanho mínimo é A3 e o arquivo deve ser enviado em PNG, PDF ou CDR.",
    pricingMode: "per_area_m2", requiresMeasurements: true, measurementUnit: "cm", requiresFile: true,
    allowedFileExtensions: ["png", "pdf", "cdr"], imageUrl: "/products/adesivo-vinil-brilho.png", imageAlt: "Adesivos impressos em vinil brilho",
    priceRules: [{ optionValue: "Vinil brilho", unitPrice: 85, minimumPrice: 35 }],
  },
  {
    name: "Adesivo transparente", slug: "adesivo-transparente", category: exampleCategories[0],
    shortDescription: "Adesivo transparente personalizado com cálculo por área.",
    description: "Informe as medidas, a quantidade e escolha com corte ou sem corte. O tamanho mínimo é A3 e o arquivo deve ser enviado em PNG, PDF ou CDR.",
    pricingMode: "per_area_m2", requiresMeasurements: true, measurementUnit: "cm", requiresFile: true,
    allowedFileExtensions: ["png", "pdf", "cdr"], imageUrl: "/products/adesivo-transparente.png", imageAlt: "Adesivos transparentes personalizados",
    priceRules: [{ optionValue: "Transparente", unitPrice: 95, minimumPrice: 45 }],
  },
  {
    name: "Adesivo DTF", slug: "adesivo-dtf", category: exampleCategories[0],
    shortDescription: "Adesivo UV DTF, feito para longa duração.",
    description: "Adesivo UV feito para longa duração. Folha A4: R$ 70,00. Folha A3: R$ 120,00. Para tamanhos maiores, entre em contato pelo WhatsApp para consultar valores.",
    pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false,
    allowedFileExtensions: [], imageUrl: "/products/adesivo-dtf.png", imageAlt: "Adesivos DTF impressos em uma máquina de produção",
    additionalImages: [{ imageUrl: "/products/adesivo-dtf-mfn.png", imageAlt: "Exemplo de adesivo UV DTF aplicado em superfície colorida" }],
    options: [{ name: "Tamanho da folha", isRequired: true, choices: ["A4", "A3"] }],
    priceRules: [{ optionValue: "A4", unitPrice: 70, minimumPrice: null }, { optionValue: "A3", unitPrice: 120, minimumPrice: null }],
  },
  { name: "Garrafa térmica inox", slug: "garrafa-termica-inox", category: exampleCategories[1], shortDescription: "Garrafa térmica inox personalizada, disponível em várias cores.", description: "Garrafa térmica em inox personalizada. Escolha a cor e digite o nome para conferir uma prévia da gravação.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/garrafa-termica-inox.png", imageAlt: "Garrafas térmicas personalizadas nas cores rosa, vermelha e preta", options: [{ name: "Cor", isRequired: true, choices: ["Preto", "Branco", "Rosa", "Vermelho", "Azul", "Laranja"] }, ...engravingOptions], priceRules: [{ optionValue: "", unitPrice: 100, minimumPrice: null }] },
  { name: "Garrafa térmica com alça", slug: "garrafa-termica-com-alca", category: exampleCategories[1], shortDescription: "Garrafa térmica com alça, em cores variadas.", description: "Garrafa térmica com alça para facilitar o transporte. Escolha a cor e digite o nome para conferir uma prévia da gravação.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/garrafa-termica-com-alca.png", imageAlt: "Garrafas térmicas com alça nas cores rosa, bege, azul e preta", options: [{ name: "Cor", isRequired: true, choices: ["Preto", "Vermelho", "Branco", "Bege", "Rosa", "Azul", "Amarelo"] }, ...engravingOptions], priceRules: [{ optionValue: "", unitPrice: 100, minimumPrice: null }] },
  { name: "Garrafa térmica com base amadeirada", slug: "garrafa-termica-base-amadeirada", category: exampleCategories[1], shortDescription: "Garrafa térmica branca com base amadeirada.", description: "Garrafa térmica branca com detalhe de base amadeirada. Digite o nome para conferir uma prévia da gravação.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/garrafa-termica-base-amadeirada.png", imageAlt: "Garrafa térmica branca com base amadeirada", options: [{ name: "Cor", isRequired: true, choices: ["Branco"] }, ...engravingOptions], priceRules: [{ optionValue: "", unitPrice: 100, minimumPrice: null }] },
  { name: "Garrafa térmica new inox", slug: "garrafa-termica-new-inox", category: exampleCategories[1], shortDescription: "Garrafa térmica inox personalizada em várias cores.", description: "Garrafa térmica new inox. Escolha a cor e informe o nome para conferir uma prévia da gravação. Consulte a equipe para confirmar disponibilidade da cor e o valor.", pricingMode: "manual", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/garrafa-termica-new-inox.png", imageAlt: "Garrafa térmica new inox rosa pastel", options: [{ name: "Cor", isRequired: true, choices: ["Preto fosco", "Vermelho", "Rosa pastel", "Amarelo", "Branco", "Verde"] }, ...engravingOptions], priceRules: [] },
  { name: "Microfone para lapela", slug: "microfone-para-lapela", category: exampleCategories[2], shortDescription: "Microfone para lapela personalizado.", description: "Microfone para lapela personalizado. Informe a quantidade desejada para solicitar o pedido.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/microfone-lapela-3d.png", imageAlt: "Microfones de lapela personalizados em duas cores", priceRules: [{ optionValue: "", unitPrice: 40, minimumPrice: null }] },
  { name: "Suporte para celular personalizado", slug: "suporte-celular-personalizado", category: exampleCategories[2], shortDescription: "Suporte para celular personalizado produzido em 3D.", description: "Suporte para celular personalizado. Informe a cor desejada nos detalhes; a disponibilidade será confirmada pela equipe no WhatsApp.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/suporte-celular-personalizado.png", imageAlt: "Suporte para celular personalizado em impressão 3D", priceRules: [{ optionValue: "", unitPrice: 20, minimumPrice: null }] },
  { name: "Totem", slug: "totem-pvc", category: exampleCategories[3], shortDescription: "Totem personalizado em PVC com cálculo por área.", description: "Informe a largura e a altura, escolha a espessura do PVC e veja uma estimativa calculada pela área do produto.", pricingMode: "per_area_m2", requiresMeasurements: true, measurementUnit: "cm", requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/totem-pvc.png", imageAlt: "Totem decorativo recortado em PVC", options: [{ name: "Espessura do PVC", isRequired: true, choices: ["1 mm", "2 mm"] }], priceRules: [{ optionValue: "1 mm", unitPrice: 220, minimumPrice: null }, { optionValue: "2 mm", unitPrice: 290, minimumPrice: null }] },
  { name: "Caneca inox", slug: "caneca-inox", category: exampleCategories[4], shortDescription: "Caneca inox personalizada com DTF ou gravação a laser.", description: "Escolha a técnica de personalização desejada: DTF ou gravação a laser. Se escolher gravação a laser, digite o nome e escolha a fonte para visualizar uma prévia.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], imageUrl: "/products/caneca-inox.png", imageAlt: "Caneca inox preta personalizada", options: [{ name: "Personalização", isRequired: true, choices: ["Gravação a laser", "DTF"] }, ...engravingOptions], priceRules: [{ optionValue: "Gravação a laser", unitPrice: 65, minimumPrice: null }, { optionValue: "DTF", unitPrice: 75, minimumPrice: null }] },
  { name: "Caneca porcelana branca", slug: "caneca-porcelana-branca", category: exampleCategories[4], shortDescription: "Caneca de porcelana branca personalizada.", description: "Caneca de porcelana branca. Se já tiver a arte pronta, anexe em PDF, PNG ou CDR. Se quiser solicitar a criação da arte, há um acréscimo de R$ 10,00 no total do pedido.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: true, allowedFileExtensions: ["pdf", "png", "cdr"], imageUrl: "/products/caneca-porcelana-branca.png", imageAlt: "Caneca de porcelana branca personalizada", options: [{ name: "Arte", isRequired: true, choices: ["Tenho arte pronta", "Quero criação da arte (+ R$ 10,00 no total)"], surchargeChoice: "Quero criação da arte (+ R$ 10,00 no total)", surchargeAmount: 10, surchargeMode: "per_order", surchargeLabel: "Criação da arte" }], priceRules: [{ optionValue: "Tenho arte pronta", unitPrice: 30, minimumPrice: null }, { optionValue: "Quero criação da arte (+ R$ 10,00 no total)", unitPrice: 30, minimumPrice: null }] },
  { name: "Caneca porcelana preta", slug: "caneca-porcelana-preta", category: exampleCategories[4], shortDescription: "Caneca de porcelana preta personalizada.", description: "Caneca de porcelana preta. Se já tiver a arte pronta, anexe em PDF, PNG ou CDR. Se quiser solicitar a criação da arte, há um acréscimo de R$ 10,00 no total do pedido.", pricingMode: "fixed", requiresMeasurements: false, measurementUnit: null, requiresFile: true, allowedFileExtensions: ["pdf", "png", "cdr"], imageUrl: "/products/caneca-porcelana-preta.png", imageAlt: "Caneca de porcelana preta personalizada", options: [{ name: "Arte", isRequired: true, choices: ["Tenho arte pronta", "Quero criação da arte (+ R$ 10,00 no total)"], surchargeChoice: "Quero criação da arte (+ R$ 10,00 no total)", surchargeAmount: 10, surchargeMode: "per_order", surchargeLabel: "Criação da arte" }], priceRules: [{ optionValue: "Tenho arte pronta", unitPrice: 40, minimumPrice: null }, { optionValue: "Quero criação da arte (+ R$ 10,00 no total)", unitPrice: 40, minimumPrice: null }] },
  { name: "Outros serviços gráficos", slug: "outros-servicos-graficos", category: exampleCategories[5], shortDescription: "Tem outra necessidade gráfica? Conte para a gente.", description: generalText, pricingMode: "manual", requiresMeasurements: false, measurementUnit: null, requiresFile: false, allowedFileExtensions: [], priceRules: [] },
];
